[bin] Rewrite drop in plain bash
Ruby no likey ed25519 keys. :-(

diff --git a/bin/executable_drop b/bin/executable_drop
--- a/bin/executable_drop
+++ b/bin/executable_drop
@@ -1,21 +1,17 @@
-#! /usr/bin/env nix-shell
-#! nix-shell -i ruby -p ruby -p rubyPackages.net-scp
+#!/usr/bin/env bash
 
-require 'open3'
-require 'pathname'
-require 'securerandom'
-require 'net/scp'
 
-file = Pathname.new(ARGV[0])
-new_name = SecureRandom.hex(12) + File.extname(file)
-abort "Och komm." unless file.exist? and file.readable?
+file="${1}"
+filename=$(basename -- "$file")
+extension="${filename##*.}"
+new_name="$(openssl rand -hex 12).${extension}"
+url="https://drop.bascht.space/${new_name}"
 
-url = "https://drop.bascht.space/#{new_name}"
+if [[ ! -f "${file}" ]]; then
+  echo "File ${file} not readable. Aborting."
+  exit 1
+fi
 
-Net::SCP.start("drop.bascht.space", "bascht") do |scp|
-  scp.upload(file.expand_path.to_s, "/home/bascht/drop/#{new_name}")
-end
-
-system "wl-copy #{url}"
-
-system("notify-send -t 1000 'Uploaded successfully' '<a href=\'#{url}\'>drop.bascht.space</a>'")
+scp "${file}" "drop.bascht.space:/home/bascht/drop/${new_name}"
+wl-copy "${url}"
+notify-send -t 1000 "Uploaded successfully" "<a href=\'${url}\'>drop.bascht.space</a>"
